// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

part of 'app_widget.dart';

List<RouteEntity> get routes => [
      RouteEntity(
        key: '/home',
        uri: Uri.parse('/home'),
        routeBuilder: b0Builder,
      ),
      RouteEntity(
        key: '/welcome',
        uri: Uri.parse('/welcome'),
        routeBuilder: b1Builder,
      ),
    ];

const routePaths = (
  path: '/',
  home: '/home',
  welcome: '/welcome',
);
